[package]
name = "tabled"
version = "0.7.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"
description = "An easy to use library for pretty print tables of Rust `struct`s and `enum`s."
repository = "https://github.com/zhiburt/tabled"
homepage = "https://github.com/zhiburt/tabled"
documentation = "https://docs.rs/tabled"
license = "MIT"
keywords = ["table", "print", "pretty-table", "format", "terminal"]
categories = ["text-processing", "visualization"]
readme = "README.md"

[workspace]
members = [
    "papergrid",
    "tabled_derive",
    "examples/terminal_table",
    "examples/show",
]

[badges]
travis-ci = { repository = "https://github.com/zhiburt/tabled", branch = "master" }
coveralls = { repository = "https://github.com/zhiburt/tabled", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[features]
color = ["papergrid/color", "ansi-str"]

[dependencies]
tabled_derive = "0.3.0"
papergrid = { path = "./papergrid" }
ansi-str = { version = "0.1.1", optional = true }

[dev-dependencies]
owo-colors = "1"
criterion = "0.3.5"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
nu-table = "0.62.0"
nu-protocol = "0.62.0"

[[bench]]
name = "table_build"
harness = false

[[example]]
name = "colored_borders"
required-features = ["color"]

[[example]]
name = "color"
required-features = ["color"]

# experement thing to check how it will work on docs.rs
[package.metadata.docs.rs]
features = ["unstable-doc"]
rustdoc-args = ["--cfg", "docsrs"]
cargo-args = ["-Zunstable-options"]
