[package]
name = "tabled"
version = "0.4.2"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"
description = "An easy to use library for pretty print tables of Rust `struct`s and `enum`s."
repository = "https://github.com/zhiburt/tabled"
homepage = "https://github.com/zhiburt/tabled"
documentation = "https://docs.rs/tabled"
license = "MIT"
keywords = ["sheet", "table", "graphics", "terminal"]
categories = ["text-processing", "visualization"]
readme = "README.md"

[workspace]
members = ["papergrid", "tabled_derive"]

[badges]
travis-ci = { repository = "https://github.com/zhiburt/tabled", branch = "master" }
coveralls = { repository = "https://github.com/zhiburt/tabled", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[features]
color = ["papergrid/color", "ansi-cut"]

[dependencies]
tabled_derive = "0.2.0"
papergrid = { path = "./papergrid" }
ansi-cut = { version = "0.2.0", optional = true }

[dev-dependencies]
owo-colors = "1"
criterion = "0.3.5"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[[bench]]
name = "table_build"
harness = false